const products = [
  {
    title: "plastic chair",
    price: 25,
    discountPercentValue: 90,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664825863/file-Auffur/tmp-7-1664825837451_wwssvi.png",
    categories: {
      "Featured Categories": ["first order deal"],
      location: ["dining"],
      features: ["chairs"],
      others: [],
    },
  },
  {
    title: "brown dining sets",
    price: 250,
    discountPercentValue: 15,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1666438205/file-Auffur/tmp-1-1666438198442_v4trpy.png",
    categories: {
      "Featured Categories": ["featured", "discounts"],
      location: ["dining"],
      features: ["chairs", "tables", "sets"],
      others: [],
    },
  },
  {
    title: "wooden tables",
    price: 125,
    discountPercentValue: 45,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664790450/file-Auffur/tmp-1-1664790412592_pogleh.png",
    categories: {
      "Featured Categories": ["featured", "discounts", "first order deal"],
      location: ["kitchen"],
      features: ["sets", "tables"],
      others: [],
    },
  },
  {
    title: "brownish  couch",
    price: 60,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664811391/file-Auffur/tmp-1-1664811267215_li5isp.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["living room"],
      features: ["chairs", "sofa"],
      others: [],
    },
  },
  {
    title: "accent table",
    price: 20,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664812297/file-Auffur/tmp-1-1664812284938_kyonay.png",
    categories: {
      "Featured Categories": [],
      location: [],
      features: ["table", "sofa"],
      others: [],
    },
  },
  {
    title: "bar table",
    price: 24,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664812647/file-Auffur/tmp-2-1664812645086_apkgpw.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["office"],
      features: [],
      others: [],
    },
  },
  {
    title: "brownish office chair",
    price: 60,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664812832/file-Auffur/tmp-3-1664812801104_kiu2og.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["office"],
      features: ["chairs"],
      others: [],
    },
  },
  {
    title: "dining set",
    price: 160,
    discountPercentValue: 10,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664812972/file-Auffur/tmp-4-1664812867715_t02ggj.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["dining"],
      features: ["tables", "chairs"],
      others: [],
    },
  },
  {
    title: "wooden kitchen desk",
    price: 40,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813327/file-Auffur/tmp-6-1664813318091_jtglsl.png",
    categories: {
      "Featured Categories": [],
      location: ["kitchen"],
      features: ["tables", "cupboards"],
      others: [],
    },
  },
  {
    title: "greyish office chair",
    price: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813292/file-Auffur/tmp-5-1664813215573_gj8z5b.png",
    categories: {
      "Featured Categories": [],
      location: ["office"],
      features: [],
      others: [],
    },
  },
  {
    title: "accent kid chair",
    price: 15,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813469/file-Auffur/tmp-7-1664813455534_st9usg.png",
    categories: {
      "Featured Categories": ["featured", "first order deal"],
      location: ["office"],
      features: ["chairs"],
      others: ["kids"],
    },
  },
  {
    title: "white side chair",
    price: 16,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813573/file-Auffur/tmp-8-1664813568107_moraqd.png",
    categories: {
      "Featured Categories": [],
      location: ["dining"],
      features: ["chairs"],
      others: [],
    },
  },
  {
    title: "accent chair",
    price: 30,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813774/file-Auffur/tmp-9-1664813725670_id5hls.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["living room"],
      features: ["chairs"],
      others: [],
    },
  },
  {
    title: "red couch",
    price: 70,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664814578/file-Auffur/tmp-14-1664814568390_wo92xf.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["living room"],
      features: ["chairs", "sofa"],
      others: [],
    },
  },
  {
    title: "leather office chair",
    price: 55,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664814124/file-Auffur/tmp-12-1664814073016_qxaoqr.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["office"],
      features: ["chairs"],
      others: [],
    },
  },
  {
    title: "yellowish armchair",
    price: 32,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813947/file-Auffur/tmp-11-1664813939182_yxvy2r.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["living room", "bedroom"],
      features: ["chairs", "sofa"],
      others: [],
    },
  },
  {
    title: "golden lamp",
    price: 22,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813904/file-Auffur/tmp-10-1664813793825_qhdb2x.png",
    categories: {
      "Featured Categories": ["first order deal"],
      location: ["living room", "bedroom"],
      features: ["lighting"],
      others: [],
    },
  },
  {
    title: "nightstand",
    price: 27,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664823309/file-Auffur/tmp-3-1664823271478_bev2ag.png",
    categories: {
      "Featured Categories": ["first order deal"],
      location: ["kitchen"],
      features: ["cupboards"],
      others: [],
    },
  },
  {
    title: "pepper mill",
    price: 5,
    discountPercentValue: 80,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813904/file-Auffur/tmp-10-1664813793825_qhdb2x.png",
    categories: {
      "Featured Categories": ["first order deal"],
      location: ["kitchen"],
      features: [],
      others: [],
    },
  },
  {
    title: "greyish couch",
    price: 76,
    discountPercentValue: 80,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664824771/file-Auffur/tmp-4-1664824711615_fe2nbg.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["living room"],
      features: ["chairs", "sofa"],
      others: [],
    },
  },
  {
    title: "multi-user workspace",
    price: 500,
    discountPercentValue: 80,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664824951/file-Auffur/tmp-5-1664824933677_m9pu0j.png",
    categories: {
      "Featured Categories": ["featured"],
      location: ["office"],
      features: ["chairs", "tables", "sets"],
      others: [],
    },
  },
  {
    title: "wooden bed frame",
    price: 67,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664825314/file-Auffur/tmp-6-1664825306530_tgylqm.png",
    categories: {
      "Featured Categories": [],
      location: ["bedroom"],
      features: [],
      others: [],
    },
  },
];

module.exports = products;
